---
# tasks file for slave-node
    - name: Launch instance
      ec2:
         aws_access_key: "AKIAZQBFUQLKOTBIJ53N"
         aws_secret_key: "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"
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         user_data: "{{ lookup('file', 'files/user_data.sh') }}"
         wait: true
         region: "{{ region }}"
         group_id: sg-04fa6c2c55662ca31
         count: 1
         instance_tags:
           Name: Ansible-Slave
      register: ec2


    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webservers
        inventory_dir: /etc/ansible/hosts
        state: present
      loop: "{{ ec2.instances }}"
      
    - name: Wait for SSH to come up
      wait_for:
           host: "{{ item.public_dns_name }}"
           port: 22
           delay: 60
           timeout: 320
           state: started
      with_items: "{{ ec2.instances }}"

