---
- hosts: localhost
  tasks:
   - name: Create a new file
     file: path=/home/webwerks/ansible/ansible.txt state=touch
   - name: copy contents
     copy:
           content: "Welcome to Neosoft Technologies"
           dest: "/home/webwerks/ansible/ansible.txt"
    
